rosbag:
  input_bag_path: '/path/to/input_bag_file'
  output_bag_path: '/path/to/output_bag_file'
  output_save_compressed_image: True
  output_storage_id: 'mcap' # 'sqlite3' or 'mcap'
grounding_dino:
  config_path: './GroundingDINO_SwinB.cfg.py'
  checkpoint_path: './groundingdino_swinb_cogcoor.pth'
  box_threshold: 0.1
  text_threshold: 0.1
  nms_threshold: 0.1
segment_anything_2:
  model_cfg: 'configs/sam2.1/sam2.1_hiera_s.yaml'
  checkpoint_path: './sam2.1_hiera_small.pt'
openclip:
  run: True
  model_name: 'ViT-B-32'
  pretrained_model: 'laion2b_s34b_b79k'
  score_threshold: 0.7
yolo:
  model: './yolo11x_anonymizer.pt'
  config_path: './yolo_config.yaml'
  confidence: 0.15
bbox_validation:
  iou_threshold: 0.9
blur:
  region: 'mask' # 'bbox' or 'mask'
  kernel_size: 31
  sigma_x: 19
debug:
  show_on_image: True
  print_on_terminal: True